Create Book Appointments Front-end
Chimwemwe-127001/book-appointment-frontend pull request #27
Opened 2022-05-11 10:38 UTC by thecodechaser

## This branch includes the following features:
- Created front-end for Book Appointments application.
- Added Redux store.
- Added Redux reducers to handle authentication and API data.
- Created Sign up and login forms.
- Created navigations.
- Created components for all pages.
- Added API-docs links.
- Applied styles
- Added responsiveness.

### Link to the backend: [Book Apponitments back-end](https://github.com/Chimwemwe-127001/book-appointment-backend)

2022-05-11 15:35 UTC, mcrd25 requested changes
Hi @thecodechaser @Buyaki01 @AnselemOdims @Chimwemwe-127001 @mwanawabangona  , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there! I really like the effort you've put into trying to follow design as much as possible. I noticed also that you sort of filled the gap with some missing pieces of the design in terms of it's feel, which is great.


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- What you need to do is remove the API doc button (a user should not even be thinking about the back-end of the application their focus is using the application to accomplish something)
- While you did a great job with the UI, remember you are following a design. In real world it's about what the client wants. They've already paid someone to design it. It's your job to develop it. That being said great job, but there is still some work to do to make it closer to design (particularly the reserve page)
- There are some things I'd like you to improve concerning the UI - see loom video: https://www.loom.com/share/78e8ad6d93bf4602b1068dd80780e852

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-05-11 15:35 UTC, mcrd25 commented on src/App.js
> +          )}
Maybe there is a cleaner way to do this?

2022-05-11 15:35 UTC, mcrd25 commented on src/components/sessions/Login.js
> +              </label>
Consider elements where that can be made into components. Try best not to repeat self with forms and Inputs or buttons. Especially when it's being used across different components. So yes Add doctor and reservation are forms but maybe form itself can be a components and input etc.

2022-05-12 07:02 UTC, thecodechaser commented
@mcrd25 Hi, Thank you for your time and feedback 😄

2022-05-12 15:49 UTC, MuriloRoque approved these changes
Hi @thecodechaser, @Buyaki01, @AnselemOdims, @Chimwemwe-127001,

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-05-12 16:02 UTC, merged

2022-05-20 16:11 UTC, mcrd25 commented
> @mcrd25 Hi, Thank you for your time and feedback 😄

Np!

If you liked my review, feel free to connect on LinkedIn and leave a skill endorsement: https://www.linkedin.com/in/mayadouglas/

You are also free to follow me on GitHub